// French and Korean interface text. Source records, names and historical figures remain unchanged.
export const memorialExtraTranslations = {
 fr: {
  viewLabel:"Parcourir le mémorial",byName:"Par nom",byUnit:"Par unité",unitLabel:"Unité / organisation",allUnits:"Toutes les unités",unitNote:"Les unités sont regroupées d’après la liste ; les variantes orthographiques évidentes sont réunies. Les unités absentes ou illisibles figurent dans « Autres ».",unitSourceNote:"Ce classement utilise les champs originaux Name et Details pour faciliter la consultation ; il ne constitue pas une vérification historique indépendante.",unitHeading:"{unit} · Entrées : {count}",unitField:"Unité",unitEmpty:"Essayez un autre nom ou choisissez Toutes les unités.",unitOtherNote:"Ces entrées ne précisent pas d’unité, ou celle-ci ne peut pas être identifiée avec certitude.",
  title:"Lisbon Maru · En mémoire des disparus",description:"Consultez le registre commémoratif du Lisbon Maru, lisez les documents originaux et déposez une fleur en hommage.",
  skip:"Aller au registre commémoratif",home:"Accueil du mémorial du Lisbon Maru",brand:"Lisbon Maru",brandSubtitle:"MÉMORIAL DU LISBON MARU",nav:"Navigation principale",roll:"Registre commémoratif",history:"Histoire et mémoire",sources:"À propos des sources",language:"Choisir la langue",
  introEyebrow:"EN MÉMOIRE · 1942",hero:["La mer a une fin.","La mémoire, non."],subtitle:"Le registre commémoratif du Lisbon Maru",intro:["Chaque nom est celui d’une vie autrefois vécue.","Lisez leurs noms. Laissez un geste de mémoire."],dedication:["Leurs noms","demeurent."],dedicatedTo:"À ceux qui ne sont pas revenus",date:"1–2 OCTOBRE 1942",sea:"Mer de Chine orientale · Lisbon Maru",wreckCoordinate:"Coordonnées de l’épave",
  rollEyebrow:"LE REGISTRE COMMÉMORATIF",rollHeading:"Chaque nom mérite d’être gardé en mémoire.",recordCount:"entrées",clickPrompt:"Choisissez un nom pour lire sa fiche et déposer une fleur",searchLabel:"Rechercher un nom ou un détail original",searchPlaceholder:"Nom, unité ou matricule…",clear:"Effacer la recherche",sort:"Noms de famille de A à Z",alphabetLabel:"Filtrer par initiale du nom de famille",all:"Tous",found:"Résultats : {count}",names:"Noms des disparus",zero:"0 entrée",read:"Lire la fiche",emptyTitle:"Aucune entrée correspondante",emptyBody:"Essayez une partie du nom ou retirez le filtre par initiale.",reset:"Afficher toutes les entrées",rollFooter:"En mémoire de chaque vie perdue.",pagination:"Pages du registre",previous:"Page précédente",next:"Page suivante",
  historyEyebrow:"UNE HISTOIRE À GARDER EN MÉMOIRE",historyHeading:["Se souvenir des vies.","Se souvenir de l’histoire."],historyLink:"Lire le récit historique de LiMMA",historyBody:["En 1942, le Lisbon Maru naviguait en mer de Chine orientale, transportant des prisonniers de guerre de Hong Kong vers le Japon. Le 1er octobre, il fut touché par une torpille d’un sous-marin américain et coula le lendemain. De nombreuses vies furent perdues. Des pêcheurs chinois des îles de Zhoushan participèrent au sauvetage des hommes tombés à la mer.","Ce mémorial commence par les noms : il rappelle les personnes derrière les chiffres et relie leur histoire à notre présent."],historySource:"Référence historique : Lisbon Maru Memorial Association (LiMMA)",
  sourcesEyebrow:"À PROPOS DES SOURCES",sourcesHeading:"À propos de cette liste",sourceBody:["Ce mémorial rassemble les {count} entrées du fichier CSV fourni. Les homonymes sont conservés séparément. L’orthographe et les abréviations sont reproduites telles qu’elles ont été fournies, sans vérification indépendante. Le nombre d’entrées décrit ce fichier, et non un bilan vérifié des décès.","Les informations personnelles proviennent des champs Name et Details. Les informations absentes portent la mention « Non indiqué dans la liste ». Des photographies et biographies complètes pourront être ajoutées lorsque des sources fiables seront disponibles."],download:"Télécharger la liste originale",footerBrand:"Lisbon Maru · En mémoire des disparus",footerNote:"Respecter la mémoire · Se souvenir pour la paix",top:"Retour en haut",
  close:"Fermer la fiche",memoryEyebrow:"EN MÉMOIRE",personDescription:"Victime du Lisbon Maru · Entrée de la liste",original:"Entrée originale",nameLabel:"Nom · Name",detailsLabel:"Informations · Details",missing:"Non indiqué dans la liste",recordNote:"Le texte original est reproduit intégralement. Les abréviations, l’orthographe et le sens des champs n’ont pas encore été vérifiés individuellement.",sourceRow:"Source : liste CSV fournie · Ligne {row}",tributeTitle:"Un geste de mémoire.",tributeBody:"Déposez une fleur en sa mémoire.",saving:"Enregistrement…",remembered:"Fleur déposée · Merci de votre hommage",flower:"Déposer une fleur",loading:"Chargement des hommages",unavailable:"Les hommages ne sont pas disponibles",flowerCount:"Hommages déposés : {count}",tributeNote:"Chaque visiteur peut déposer une fleur par personne.",retry:"Réessayer",readError:"Impossible de charger les hommages. Veuillez réessayer plus tard.",saveError:"Votre fleur n’a pas pu être enregistrée. Veuillez réessayer.",closing:"Qu’ils reposent en paix. Que leur mémoire demeure.",closingEnglish:"NOUS NOUS SOUVIENDRONS D’EUX",toolTitle:"Rechercher dans le registre",toolDescription:"Rechercher un nom ou un détail original et mettre à jour les entrées affichées.",toolError:"Saisissez une recherche de 120 caractères au maximum",
 },
 ko: {
  viewLabel:"추모 명부 보기",byName:"이름별 보기",byUnit:"소속별 보기",unitLabel:"부대 / 소속 기관",allUnits:"모든 소속",unitNote:"명부에 적힌 소속을 기준으로 분류하며, 명확한 철자 차이는 같은 항목으로 묶었습니다. 소속이 없거나 판독할 수 없는 기록은 ‘기타’에 포함됩니다.",unitSourceNote:"소속 분류는 Name과 Details 원문을 바탕으로 한 열람용 정리이며, 독립적인 역사 검증을 의미하지 않습니다.",unitHeading:"{unit} · 기록 {count}건",unitField:"소속 분류",unitEmpty:"다른 이름을 검색하거나 ‘모든 소속’을 선택하세요.",unitOtherNote:"소속이 명시되어 있지 않거나 원문의 소속명을 확실하게 식별할 수 없는 기록입니다.",
  title:"리스본 마루호 · 추모 기록",description:"리스본 마루호 희생자 명부와 원문 기록을 읽고, 추모의 꽃을 바칠 수 있습니다.",
  skip:"추모 명부로 이동",home:"리스본 마루호 추모 사이트 홈",brand:"리스본 마루호",brandSubtitle:"리스본 마루호 추모 사이트",nav:"주요 메뉴",roll:"희생자 명부",history:"역사와 기억",sources:"자료 안내",language:"언어 선택",
  introEyebrow:"추모 · 1942",hero:["바다에는 끝이 있지만,","기억에는 없습니다."],subtitle:"리스본 마루호 희생자 추모 명부",intro:["모든 이름에는 한때 살아 있던 한 사람의 삶이 있습니다.","그들의 이름을 읽고 추모의 마음을 남겨 주세요."],dedication:["그들의 이름을","기억합니다."],dedicatedTo:"돌아오지 못한 이들에게",date:"1942년 10월 1–2일",sea:"동중국해 · 리스본 마루호",wreckCoordinate:"침몰 지점 좌표",
  rollEyebrow:"추모 명부",rollHeading:"한 사람 한 사람의 이름을 기억합니다.",recordCount:"건의 기록",clickPrompt:"이름을 선택하면 기록을 읽고 꽃을 바칠 수 있습니다",searchLabel:"이름 또는 원문 기록 검색",searchPlaceholder:"이름, 소속 부대, 군번 검색…",clear:"검색 지우기",sort:"성의 알파벳순 A–Z",alphabetLabel:"성의 첫 글자로 필터링",all:"전체",found:"기록 {count}건을 찾았습니다",names:"희생자의 이름",zero:"기록 0건",read:"기록 읽기",emptyTitle:"일치하는 기록이 없습니다",emptyBody:"이름의 일부로 검색하거나 첫 글자 필터를 해제하세요.",reset:"모든 기록 보기",rollFooter:"희생된 모든 이의 삶을 기리며.",pagination:"추모 명부 페이지",previous:"이전 페이지",next:"다음 페이지",
  historyEyebrow:"기억해야 할 역사",historyHeading:["삶을 기억하고,","역사를 기억합니다."],historyLink:"LiMMA 역사 자료 읽기",historyBody:["1942년 리스본 마루호는 홍콩에서 일본으로 이송되는 전쟁포로들을 태우고 동중국해를 항해했습니다. 10월 1일 미국 잠수함의 어뢰에 맞았으며, 다음 날 침몰했습니다. 많은 사람이 목숨을 잃었고, 중국 저우산 제도의 어민들이 바다에 빠진 사람들을 구조했습니다.","이 추모 명부는 이름에서 시작합니다. 숫자 뒤에 있던 한 사람 한 사람을 기억하며, 그들의 역사를 오늘의 우리와 연결합니다."],historySource:"역사 참고 자료: Lisbon Maru Memorial Association(LiMMA)",
  sourcesEyebrow:"기록 안내",sourcesHeading:"이 명부에 대하여",sourceBody:["제공된 CSV 파일의 기록 {count}건을 모두 수록했습니다. 이름이 같은 기록도 각각 보존하며, 독립적으로 확인되지 않은 철자와 약어는 원문 그대로 표시합니다. 기록 수는 이 파일에 수록된 항목 수이며, 확인된 전체 희생자 수를 뜻하지 않습니다.","인물 정보는 명부의 Name과 Details 항목에서 가져왔습니다. 정보가 없는 경우 ‘명부에 기재되지 않음’으로 표시합니다. 사진과 상세한 생애는 신뢰할 수 있는 자료를 확보한 뒤 추가할 수 있습니다."],download:"원본 명부 내려받기",footerBrand:"리스본 마루호 · 추모 기록",footerNote:"기억을 존중하며 · 평화를 바라며",top:"맨 위로",
  close:"인물 기록 닫기",memoryEyebrow:"추모의 마음을 담아",personDescription:"리스본 마루호 희생자 · 명부 기록",original:"명부 원문 기록",nameLabel:"이름 · Name",detailsLabel:"상세 정보 · Details",missing:"명부에 기재되지 않음",recordNote:"원본 명부의 기록을 그대로 표시합니다. 약어, 철자, 각 항목의 의미는 아직 개별적으로 검증되지 않았습니다.",sourceRow:"출처: 제공된 희생자 CSV 명부 · {row}행",tributeTitle:"이 이름에 추모의 마음을 남겨 주세요.",tributeBody:"한 송이 꽃을 바쳐 추모해 주세요.",saving:"저장 중…",remembered:"꽃을 바쳤습니다 · 기억해 주셔서 감사합니다",flower:"꽃 바치기",loading:"헌화 기록을 불러오는 중",unavailable:"헌화 기록을 불러올 수 없습니다",flowerCount:"추모의 마음 {count}건이 남겨졌습니다",tributeNote:"방문자 한 명당 각 인물에게 한 번 헌화할 수 있습니다.",retry:"다시 시도",readError:"헌화 기록을 불러올 수 없습니다. 잠시 후 다시 시도해 주세요.",saveError:"헌화를 저장하지 못했습니다. 다시 시도해 주세요.",closing:"평안히 잠드시길. 그 기억이 오래도록 이어지길.",closingEnglish:"우리는 그들을 기억하겠습니다",toolTitle:"추모 명부 검색",toolDescription:"이름 또는 원문 기록을 검색하고 표시되는 명부를 갱신합니다.",toolError:"검색어는 120자 이내로 입력해 주세요",
 },
} as const;

export const historicalExtraTranslations = {
 fr: {
  nav:"Données historiques",eyebrow:"DES VIES DERRIÈRE LES CHIFFRES",title:"Derrière chaque chiffre, une vie.",introduction:"Les prisonniers britanniques à bord du Lisbon Maru et leur sort après le sauvetage.",interactionHint:"Choisissez une partie du graphique ou sa légende pour la mettre en évidence. Choisissez-la à nouveau ou appuyez sur Échap pour annuler.",selected:"Sélection : {label}, {count} personnes, {percent}.",allVisible:"Toutes les catégories sont affichées.",aboard:"Prisonniers britanniques à bord",casualties:"Pertes et sauvetage des prisonniers britanniques",died:"Décédés",other:"Capturés par les forces japonaises (hors sauvetage par les pêcheurs)",rescued:"Secourus par les pêcheurs chinois",waffleDescription:"Graphique de 100 points : environ 46 % de décès, 33 % de capturés hors sauvetage par les pêcheurs et 21 % secourus par les pêcheurs chinois.",waffleNote:"Chaque point représente environ 1 % du total. Les pourcentages sont arrondis.",fate:"Après le sauvetage",fateBody:"Parmi les 384 hommes secourus par les pêcheurs chinois, seuls trois échappèrent à une nouvelle capture.",ringDescription:"Sur les 384 hommes secourus, 381 furent repris par les forces japonaises et trois échappèrent à une nouvelle capture, soit environ 0,78 %.",escapedShare:"Part ayant échappé à une nouvelle capture",recaptured:"Secourus, puis repris par les forces japonaises",escaped:"Ayant échappé à une nouvelle capture",exactShare:"Environ 0,78 % · 3 / 384",contextTitle:"Comment lire ces chiffres",context:"Le graphique de gauche reprend les catégories de l’infographie fournie. Les groupes de 604 et 384 distinguent les parcours de sauvetage initiaux, et non le sort final. Sur les 384 secourus par les pêcheurs, 381 furent ensuite repris par les forces japonaises.",source:"Référence : Lisbon Maru Memorial Association (LiMMA). Son récit indique 1 816, 828, 384 et trois ; 604 est calculé par 1 816 − 828 − 384, et 381 par 384 − 3.",rosterNote:"Le bilan historique de 828 décès et les {count} entrées CSV de ce mémorial ne mesurent pas la même chose. Le nombre d’entrées n’est pas le bilan total des décès.",sourceLink:"Lire le récit historique",
 },
 ko: {
  nav:"역사 통계",eyebrow:"숫자 뒤에 있던 삶",title:"숫자 뒤에는 한 사람의 삶이 있습니다.",introduction:"리스본 마루호에 탑승했던 영국인 전쟁포로와 구조 이후의 운명을 살펴봅니다.",interactionHint:"그래프나 범례를 선택하면 해당 분류가 강조됩니다. 다시 선택하거나 Esc를 누르면 해제됩니다.",selected:"선택: {label}, {count}명, {percent}.",allVisible:"모든 분류를 표시하고 있습니다.",aboard:"탑승한 영국인 전쟁포로",casualties:"영국인 전쟁포로의 희생과 구조",died:"사망",other:"일본군에 붙잡힘(어민 구조자 제외)",rescued:"중국 어민에게 구조됨",waffleDescription:"100개 점으로 표시한 그래프: 사망 약 46%, 어민 구조자를 제외한 일본군 포로 약 33%, 중국 어민에게 구조된 사람 약 21%.",waffleNote:"점 하나는 전체의 약 1%를 나타냅니다. 비율은 반올림했습니다.",fate:"구조 이후의 운명",fateBody:"중국 어민에게 구조된 384명 중 다시 붙잡히지 않고 탈출한 사람은 3명뿐이었습니다.",ringDescription:"어민에게 구조된 384명 중 381명은 일본군에 다시 붙잡혔고, 3명은 재포획을 피했습니다. 그 비율은 약 0.78%입니다.",escapedShare:"재포획을 피한 비율",recaptured:"구조 후 일본군에 다시 붙잡힘",escaped:"재포획을 피함",exactShare:"약 0.78% · 3 / 384",contextTitle:"숫자를 읽는 방법",context:"왼쪽 그래프는 제공된 정보 그림의 분류를 따릅니다. 604명과 384명은 당시 구조 경로를 구분하며, 최종 운명을 나타내지 않습니다. 어민에게 구조된 384명 중 381명은 이후 일본군에 다시 붙잡혔습니다.",source:"역사 참고: Lisbon Maru Memorial Association(LiMMA). 협회 자료의 1,816명, 828명, 384명, 3명을 사용했습니다. 604는 1,816 − 828 − 384, 381은 384 − 3으로 계산합니다.",rosterNote:"역사 자료의 희생자 828명과 이 명부의 CSV 기록 {count}건은 집계 기준이 다릅니다. 파일의 기록 수는 전체 희생자 수가 아닙니다.",sourceLink:"역사 자료 읽기",
 },
} as const;

export const shipHoldExtraTranslations = {
 fr: {
  nav:"Cales et prisonniers",eyebrow:"À BORD DU LISBON MARU",title:"Les hommes sous le pont.",intro:"Choisissez l’icône du navire pour découvrir les prisonniers et leurs unités dans les trois cales.",open:"Ouvrir les cales",close:"Fermer les informations des cales",iconAlt:"Icône du Lisbon Maru",iconCaption:"LISBON MARU",promptTitle:"Au-delà de la silhouette du navire.",prompt:"Ouvrez le navire, puis choisissez une cale pour consulter ses effectifs, ses unités et sa part des prisonniers.",panel:"Prisonniers de guerre dans les cales",select:"Choisir une cale",hold:"Cale n° {id}",share:"Part des prisonniers à bord",distribution:"Répartition des prisonniers par cale",selected:"Cale affichée : {hold}, {count} personnes, {percent} % des prisonniers.",unitHeading:"Unités et effectifs indiqués dans les notes",unitNames:{royalNavy:"Marine royale britannique",royalScots:"Régiment Royal Scots",middlesex:"Régiment du Middlesex",royalEngineers:"Corps royal du génie",royalSignals:"Corps royal des transmissions",other:"Autres (non précisés dans les notes)",royalArtillery:"Artillerie royale"},population:"Prisonniers dans cette cale",people:"personnes",unitLabel:"Unité",countLabel:"Effectif",totalLabel:"Total de la cale",noteBasis:"D’après les notes fournies",source:"Les effectifs et unités sont transcrits des notes manuscrites fournies, soit {total} prisonniers dans les trois cales. Les parts arrondies de 20 % / 59 % / 21 % indiquent la répartition des prisonniers, et non les taux de décès.",graphicNote:"L’icône fournie sert à ouvrir les informations ; elle ne représente pas un plan exact du navire ni la position des cales.",reference:"Contexte historique complémentaire : Lisbon Maru Memorial Association (LiMMA).",sourceLink:"Lire l’histoire des cales",
 },
 ko: {
  nav:"선창과 전쟁포로",eyebrow:"리스본 마루호의 선내",title:"갑판 아래에 있던 사람들.",intro:"배 아이콘을 선택해 세 선창에 수용된 전쟁포로의 분포와 소속 부대를 살펴보세요.",open:"선창 정보 열기",close:"선창 정보 닫기",iconAlt:"리스본 마루호 배 아이콘",iconCaption:"리스본 마루호",promptTitle:"배의 윤곽 너머, 선창에 있던 삶으로.",prompt:"정보를 펼친 뒤 선창을 선택하면 인원, 소속 부대와 수용 비율을 볼 수 있습니다.",panel:"선창에 수용된 전쟁포로 정보",select:"선창 선택",hold:"제{id}선창",share:"탑승 전쟁포로 중 비율",distribution:"선창별 전쟁포로 분포",selected:"표시 중: {hold}, {count}명, 전쟁포로의 {percent}%.",unitHeading:"노트에 기록된 소속 부대와 인원",unitNames:{royalNavy:"영국 왕립해군",royalScots:"로열 스코츠 연대",middlesex:"미들섹스 연대",royalEngineers:"왕립공병대",royalSignals:"왕립통신대",other:"기타(노트에 세부 내역 없음)",royalArtillery:"왕립포병대"},population:"이 선창의 전쟁포로 수",people:"명",unitLabel:"부대 / 소속",countLabel:"인원",totalLabel:"선창 합계",noteBasis:"제공된 노트 기준",source:"인원과 소속은 제공된 손글씨 노트를 옮긴 것으로, 세 선창의 합계는 {total}명입니다. 20% / 59% / 21%는 수용 인원의 비율을 반올림한 값이며, 희생자 비율이 아닙니다.",graphicNote:"제공된 배 아이콘은 정보를 여는 입구로 사용합니다. 실제 배의 정확한 구조나 선창 위치를 나타내지 않습니다.",reference:"추가 역사 참고: Lisbon Maru Memorial Association(LiMMA).",sourceLink:"선창 역사 자료 읽기",
 },
} as const;

export const geographyExtraTranslations = {
 fr: {
  nav:"Lieux et voyage",eyebrow:"UN LIEU DANS NOTRE MÉMOIRE",subtitle:"Épave du Lisbon Maru · Au large de Dongji, Zhoushan, Zhejiang, Chine",introduction:"Partez du globe et suivez les lieux liés à ce voyage.",globeLabel:"Globe interactif du voyage du Lisbon Maru",countriesLabel:"Légende des pays, du territoire et de l’épave",globeHint:"Choisissez un pays, une légende ou un lieu pour le mettre en évidence. Faites glisser horizontalement ou utilisez les flèches pour tourner le globe.",play:"Lancer le récit",pause:"Mettre le récit en pause",replay:"Repartir du globe",previous:"Lieu précédent",next:"Lieu suivant",zoomIn:"Agrandir la carte",zoomOut:"Réduire la carte",loading:"Chargement du globe…",loadError:"La carte n’a pas pu être chargée. Les descriptions des lieux restent accessibles.",retry:"Recharger la carte",placesLabel:"Choisir un lieu",storyLabel:"Le récit de chaque lieu",step:"{current} / {total}",auto:"Récit en cours",manual:"Exploration libre",finished:"Fin du récit",china:"Chine",japan:"Japon",hk:"Hong Kong (britannique)",wreck:"Site du naufrage",voyage:"De Hong Kong (britannique) à la zone du naufrage (schéma)",planned:"Direction prévue vers le Japon (schéma)",names:["Le globe et la mer de Chine orientale","Hong Kong (britannique)","Coordonnées de l’épave","Les îles de Dongji","Port de Moji · Japon"],roles:["Vue mondiale","Lieu de départ","Là où le voyage s’arrêta","Lieu du sauvetage par les pêcheurs","Destination jamais atteinte"],dates:["1942 · Les lieux de mémoire","27 septembre 1942","1–2 octobre 1942","2 octobre 1942","Le voyage prévu vers le Japon"],stories:["Hong Kong, la mer de Chine orientale et le Japon : des lieux reliés par les vies des prisonniers, des disparus et des pêcheurs qui leur portèrent secours.","Le Lisbon Maru quitta Hong Kong avec 1 816 prisonniers de guerre britanniques, transférés vers le Japon.","Touché par une torpille le 1er octobre, le navire coula le lendemain. Le repère utilise les coordonnées de l’épave rapportées dans l’entretien de Fang Li.","Les pêcheurs de Qingbang et de Miaozihu, dans les îles de Dongji, secoururent 384 hommes. L’épave se trouve dans les eaux voisines.","Le voyage devait se poursuivre vers le port japonais de Moji. Le Lisbon Maru coula en chemin et n’y parvint jamais."],mapNote:"Les lignes indiquent les liens géographiques entre les lieux, et non une reconstitution précise du trajet. Hong Kong, les îles et le port sont situés approximativement ; l’épave utilise les coordonnées indiquées ci-dessus. Le fond de carte montre le littoral moderne.",coordinateSource:"Coordonnées : entretien de Fang Li · The Paper",historySource:"Voyage et sauvetage : LiMMA",destinationSource:"Moji : Richard Graham · Pen & Sword",mapSource:"Fond de carte : Natural Earth",
 },
 ko: {
  nav:"지리와 항해",eyebrow:"기억 속의 장소",subtitle:"리스본 마루호 침몰 지점 · 중국 저장성 저우산 둥지 제도 인근 해역",introduction:"지구에서 출발해 이 항해와 연결된 장소들을 따라가 봅니다.",globeLabel:"리스본 마루호 지리 인터랙티브 지구본",countriesLabel:"국가, 지역 및 침몰 지점 범례",globeHint:"국가, 범례 또는 장소를 선택하면 서로 연결되어 강조됩니다. 좌우로 끌거나 방향키로 지구본을 회전하세요.",play:"자동 해설 시작",pause:"해설 일시 정지",replay:"지구에서 다시 시작",previous:"이전 장소",next:"다음 장소",zoomIn:"지도 확대",zoomOut:"지도 축소",loading:"지구 지도를 불러오는 중…",loadError:"지도를 불러올 수 없습니다. 장소 설명은 계속 읽을 수 있습니다.",retry:"지도 다시 불러오기",placesLabel:"장소 선택",storyLabel:"장소별 이야기",step:"{current} / {total}",auto:"자동 해설 중",manual:"직접 둘러보기",finished:"해설 종료",china:"중국",japan:"일본",hk:"홍콩(영국령)",wreck:"침몰 지점",voyage:"홍콩(영국령)에서 침몰 해역까지(개략도)",planned:"계획된 일본행 방향(개략도)",names:["지구와 동중국해","홍콩(영국령)","침몰 좌표","둥지 제도 일대","모지항 · 일본"],roles:["세계적 시야","출항 장소","항해가 끝난 곳","어민의 구조 현장","도달하지 못한 목적지"],dates:["1942 · 기억 속의 항해","1942년 9월 27일","1942년 10월 1–2일","1942년 10월 2일","계획된 일본행 항해"],stories:["홍콩, 동중국해, 일본. 이 장소들은 전쟁포로, 희생자, 그리고 도움의 손길을 내민 어민들의 삶으로 연결됩니다.","리스본 마루호는 일본으로 이송되는 영국인 전쟁포로 1,816명을 태우고 홍콩에서 출항했습니다.","배는 10월 1일 어뢰에 맞아 다음 날 침몰했습니다. 지도에는 팡리의 인터뷰에서 제시된 침몰 좌표를 표시했습니다.","저장성 저우산 둥지 제도의 칭방섬과 먀오쯔후섬 어민들이 384명을 구조했습니다. 침몰 지점은 인근 해역에 있습니다.","원래 항해 목적지는 일본 모지항이었습니다. 리스본 마루호는 도중에 침몰하여 이곳에 도달하지 못했습니다."],mapNote:"선은 장소 사이의 지리적 관계를 나타내며, 실제 항로를 정확히 복원한 것이 아닙니다. 홍콩, 섬, 항구는 대략적인 위치이고 침몰 지점은 위 좌표를 사용합니다. 바탕 지도는 현대 해안선을 보여 줍니다.",coordinateSource:"침몰 좌표: 팡리 인터뷰 · The Paper",historySource:"항해와 구조: LiMMA",destinationSource:"모지항: Richard Graham · Pen & Sword",mapSource:"바탕 지도: Natural Earth",
 },
} as const;

export const topologyExtraTranslations = {
 fr: {
  nav:"Schéma de l’événement",eyebrow:"LES LIENS ENTRE LES VIES",title:"Un voyage, tant de destins.",intro:"Suivez les branches du voyage prévu au naufrage, au sauvetage et à ses suites.",hint:"Choisissez un nœud ou une légende pour suivre ses branches et lire son histoire. Choisissez à nouveau ou appuyez sur Échap pour tout afficher.",scrollHint:"Faites défiler horizontalement pour explorer tout le schéma.",diagramLabel:"Schéma des événements du Lisbon Maru",legendLabel:"Légende du schéma",selectLabel:"Choisir un événement",overview:"Tous les événements",reset:"Tout afficher",detailLabel:"À propos de cet événement",sourceLink:"Lire la source",fishermenUnit:"pêcheurs",rescuedMeta:"384 prisonniers secourus",categories:{planned:"Voyage prévu",actual:"Événements et suites",place:"Lieu",attack:"Attaque et naufrage",death:"Décédés",captive:"Capturés",survivor:"Secourus / échappés",rescue:"Sauvetage des pêcheurs"},categoryDescriptions:{planned:"La ligne en pointillés vers Moji représente le voyage prévu. Le Lisbon Maru n’atteignit jamais le Japon.",actual:"Les lignes continues relient les événements et les destins qui suivirent ; elles ne sont pas un trajet maritime précis.",place:"Les doubles cercles marquent Hong Kong, Dongji, Moji et le Royaume-Uni, reliant le départ, le sauvetage et les voyages ultérieurs.",attack:"Touché par une torpille le 1er octobre 1942, le navire coula le lendemain.",death:"828 prisonniers britanniques moururent, soit environ 46 % de ceux à bord.",captive:"Les 604 hommes suivent un parcours initial distinct du sauvetage par les pêcheurs. Sur les 384 secourus par les pêcheurs, 381 furent repris ensuite.",survivor:"384 désigne les hommes secourus par les pêcheurs ; trois désigne ceux ayant échappé à une nouvelle capture. Il s’agit de deux étapes, pas du même sort final.",rescue:"198 pêcheurs participèrent au sauvetage de 384 prisonniers britanniques."},nodes:{
   hongkong:{title:"Hong Kong (britannique)",meta:"27 septembre 1942 · 1 816 prisonniers britanniques",body:"Le Lisbon Maru quitta Hong Kong pour le transfert des prisonniers vers le Japon.",source:"history"},
   moji:{title:"Port de Moji, Japon",meta:"La destination jamais atteinte",body:"Moji était la destination prévue du voyage. La ligne en pointillés indique le projet, et non une traversée achevée.",source:"destination"},
   dongji:{title:"Dongji, Zhejiang",meta:"Zhoushan · Qingbang et Miaozihu",body:"L’épave se trouve dans les eaux voisines. Les pêcheurs de ces îles secoururent les prisonniers et prirent soin d’eux.",source:"history"},
   attack:{title:"Attaque et naufrage",meta:"1–2 octobre 1942",body:"L’USS Grouper torpilla le navire, qui coula le lendemain. Cet événement conduit aux branches ci-dessous.",source:"history"},
   died:{title:"Décédés",meta:"828 personnes · Environ 46 %",body:"828 prisonniers britanniques moururent pendant le voyage, le naufrage et les violences qui l’accompagnèrent.",source:"history"},
   captured:{title:"Capturés, hors sauvetage par les pêcheurs",meta:"604 personnes · Environ 33 %",body:"Calculé par 1 816 − 828 − 384, selon la section des données historiques. La distinction porte sur le parcours de sauvetage initial.",source:"history"},
   rescued:{title:"Secourus par les pêcheurs chinois",meta:"384 personnes · Environ 21 %",body:"Ce nombre désigne les hommes sortis de la mer. Pour 381 d’entre eux, le sauvetage fut suivi d’une nouvelle capture.",source:"history"},
   rescue:{title:"Sauvetage des pêcheurs",meta:"198 pêcheurs · 384 prisonniers secourus",body:"Les pêcheurs de Qingbang et de Miaozihu sortirent à plusieurs reprises en mer et soignèrent les rescapés. 198 compte les sauveteurs ; 384 compte les prisonniers secourus.",source:"fishermen"},
   recaptured:{title:"Secourus, puis repris",meta:"381 personnes · 384 − 3",body:"381 des hommes secourus par les pêcheurs furent ensuite repris par les forces japonaises. Ce groupe fait partie des 384.",source:"history"},
   escaped:{title:"Ayant échappé à une nouvelle capture",meta:"3 personnes · Environ 0,78 % de 384",body:"Fallace, Johnstone et Evans furent cachés par les habitants, puis aidés à quitter les îles et à gagner la sécurité par la Chine continentale.",source:"history"},
   britain:{title:"Royaume-Uni",meta:"Schéma des voyages ultérieurs",body:"Il ne s’agit pas d’un voyage direct de Dongji au Royaume-Uni. Evans passa par l’Inde et le Canada avant de se rendre en Angleterre en 1945.",source:"escape"},
  },note:"Ce schéma relie les événements : la taille des nœuds ne représente pas les effectifs et les lignes ne sont pas des trajets précis. Les pourcentages sont arrondis. 381 et trois sont des sous-groupes de 384, et non des totaux à ajouter. Le lien vers le Royaume-Uni indique les voyages ultérieurs, pas une traversée directe commune aux trois évadés.",sourcesTitle:"Sources historiques",historySource:"Voyage et chiffres · LiMMA",fishermenSource:"198 pêcheurs · Témoignages recueillis par Xinhua",escapeSource:"Voyages ultérieurs · Fiche personnelle d’Evans",destinationSource:"Moji · Richard Graham",
 },
 ko: {
  nav:"사건 관계도",eyebrow:"삶을 연결하는 사건들",title:"하나의 항해, 서로 다른 운명.",intro:"계획된 항해에서 침몰, 구조, 그 이후까지 사건의 분기를 따라가 봅니다.",hint:"노드나 범례를 선택하면 관련 분기와 설명을 볼 수 있습니다. 다시 선택하거나 Esc를 누르면 전체가 표시됩니다.",scrollHint:"좌우로 스크롤해 전체 관계도를 살펴보세요.",diagramLabel:"리스본 마루호 사건 관계도",legendLabel:"관계도 범례",selectLabel:"사건 선택",overview:"전체 사건",reset:"전체 보기",detailLabel:"사건 설명",sourceLink:"자료 읽기",fishermenUnit:"명의 어민",rescuedMeta:"전쟁포로 384명 구조",categories:{planned:"계획된 항해",actual:"사건과 그 이후",place:"장소",attack:"피격과 침몰",death:"사망",captive:"포획",survivor:"구조 / 탈출",rescue:"어민의 구조"},categoryDescriptions:{planned:"모지항으로 향하는 점선은 계획된 항해를 뜻합니다. 리스본 마루호는 일본에 도달하지 못했습니다.",actual:"실선은 사건과 이후의 운명을 연결하며, 정확한 항로를 나타내지 않습니다.",place:"겹친 두 원은 홍콩, 둥지 제도, 모지항, 영국을 나타내며 출항, 구조와 이후 여정을 연결합니다.",attack:"배는 1942년 10월 1일 어뢰에 맞아 다음 날 침몰했습니다.",death:"영국인 전쟁포로 828명이 사망했으며, 탑승 인원의 약 46%입니다.",captive:"604명은 어민 구조와 다른 초기 경로를 나타냅니다. 어민에게 구조된 384명 중 381명은 이후 다시 붙잡혔습니다.",survivor:"384는 어민에게 구조된 인원이고 3은 재포획을 피한 인원입니다. 서로 다른 단계의 수치이며 같은 최종 결과를 뜻하지 않습니다.",rescue:"어민 198명이 영국인 전쟁포로 384명의 구조에 참여했습니다."},nodes:{
   hongkong:{title:"홍콩(영국령)",meta:"1942년 9월 27일 · 영국인 전쟁포로 1,816명",body:"리스본 마루호는 전쟁포로를 일본으로 이송하기 위해 홍콩에서 출항했습니다.",source:"history"},
   moji:{title:"모지항, 일본",meta:"도달하지 못한 목적지",body:"모지항은 원래 예정된 일본행 목적지입니다. 점선은 계획을 나타내며 완료된 항해가 아닙니다.",source:"destination"},
   dongji:{title:"저장성 둥지 제도",meta:"저우산 · 칭방섬과 먀오쯔후섬",body:"침몰 지점은 인근 해역에 있습니다. 이 섬들의 어민들이 전쟁포로를 구조하고 돌보았습니다.",source:"history"},
   attack:{title:"피격과 침몰",meta:"1942년 10월 1–2일",body:"미국 잠수함 USS Grouper의 어뢰에 맞은 배는 다음 날 침몰했습니다. 이 사건에서 이후의 운명이 갈라집니다.",source:"history"},
   died:{title:"사망",meta:"828명 · 약 46%",body:"영국인 전쟁포로 828명이 항해와 침몰, 그와 관련된 폭력으로 목숨을 잃었습니다.",source:"history"},
   captured:{title:"포획(어민 구조자 제외)",meta:"604명 · 약 33%",body:"역사 통계와 같이 1,816 − 828 − 384로 계산했습니다. 당시 구조 경로의 차이를 구분한 수치입니다.",source:"history"},
   rescued:{title:"중국 어민에게 구조됨",meta:"384명 · 약 21%",body:"바다에서 구조된 사람의 수입니다. 이 중 381명은 이후 일본군에 다시 붙잡혔습니다.",source:"history"},
   rescue:{title:"어민의 구조",meta:"어민 198명 · 전쟁포로 384명 구조",body:"칭방섬과 먀오쯔후섬 어민들은 반복해서 바다로 나가 사람들을 구조하고 돌보았습니다. 198은 구조한 어민 수, 384는 구조된 전쟁포로 수입니다.",source:"fishermen"},
   recaptured:{title:"구조 후 재포획",meta:"381명 · 384 − 3",body:"어민에게 구조된 384명 중 381명이 이후 일본군에 다시 붙잡혔습니다.",source:"history"},
   escaped:{title:"재포획을 피함",meta:"3명 · 384명의 약 0.78%",body:"Fallace, Johnstone, Evans는 주민들의 도움으로 몸을 숨긴 뒤 섬을 떠나 중국 본토를 거쳐 탈출했습니다.",source:"history"},
   britain:{title:"영국",meta:"이후 여정의 개략도",body:"둥지 제도에서 영국으로 직행한 항로가 아닙니다. Evans는 인도와 캐나다를 거쳐 1945년 영국을 방문했습니다.",source:"escape"},
  },note:"사건 관계도이므로 노드의 크기는 인원 비율, 선은 정확한 항로를 나타내지 않습니다. 비율은 반올림했습니다. 381명과 3명은 384명에 포함되므로 중복하여 합산하지 않습니다. 영국으로 향하는 선은 이후의 여정이며, 세 사람이 함께 직행했다는 뜻이 아닙니다.",sourcesTitle:"역사 참고 자료",historySource:"항해와 인원 · LiMMA",fishermenSource:"어민 198명 · 신화통신 목격자 취재",escapeSource:"이후 여정 · Evans 개인 기록",destinationSource:"모지항 · Richard Graham",
 },
} as const;

export const extraUnitNames = {
 fr:{"hong-kong-singapore-artillery":"Artillerie royale de Hong Kong et de Singapour","hong-kong-naval-volunteer-reserve":"Réserve navale volontaire royale de Hong Kong","naval-dockyard-police":"Police des arsenaux de la Marine royale","hong-kong-dockyard-defence":"Corps de défense de l’arsenal de Hong Kong","hong-kong-police":"Police de Hong Kong","army-medical-corps":"Corps royal de santé de l’armée","army-dental-corps":"Corps royal dentaire de l’armée","royal-marines":"Fusiliers marins britanniques","royal-signals":"Corps royal des transmissions","royal-artillery":"Artillerie royale","royal-navy":"Marine royale britannique","royal-scots":"Régiment Royal Scots",middlesex:"Régiment du Middlesex","royal-engineers":"Corps royal du génie","st-john-ambulance":"Ambulance Saint-Jean","merchant-navy":"Marine marchande",other:"Autres"},
 ko:{"hong-kong-singapore-artillery":"홍콩·싱가포르 왕립포병대","hong-kong-naval-volunteer-reserve":"홍콩 왕립해군 의용예비대","naval-dockyard-police":"왕립해군 조선소 경찰","hong-kong-dockyard-defence":"홍콩 조선소 방위대","hong-kong-police":"홍콩 경찰","army-medical-corps":"왕립육군 의무대","army-dental-corps":"왕립육군 치과대","royal-marines":"영국 왕립해병대","royal-signals":"왕립통신대","royal-artillery":"왕립포병대","royal-navy":"영국 왕립해군","royal-scots":"로열 스코츠 연대",middlesex:"미들섹스 연대","royal-engineers":"왕립공병대","st-john-ambulance":"세인트 존 구급대","merchant-navy":"상선대",other:"기타"},
} as const;
