import { memorialNewTranslations } from "./new-locales";
import { memorialExtraTranslations } from "./extra-locales";
export const supportedLocales = ["zh", "en", "ja", "fr", "ko", "es", "ar"] as const;
export type Locale = typeof supportedLocales[number];
export const languageNames = {zh:"中文",en:"English",ja:"日本語",fr:"Français",ko:"한국어",es:"Español",ar:"العربية"} as const;
export const validLocale = (value: unknown): value is Locale => typeof value === "string" && supportedLocales.some(locale => locale === value);
export const languageDirections = {zh:"ltr",en:"ltr",ja:"ltr",fr:"ltr",ko:"ltr",es:"ltr",ar:"rtl"} as const;
export const languageTags = {zh:"zh-CN",en:"en",ja:"ja",fr:"fr",ko:"ko",es:"es",ar:"ar"};
export const translations = {
 ...memorialNewTranslations,
 ...memorialExtraTranslations,
 zh: {
  viewLabel:"查看方式",byName:"按姓名查看",byUnit:"按部队单位查看",unitLabel:"部队 / 单位",allUnits:"全部单位",unitNote:"依据名单中的单位文字归类，明确的拼写差异合并显示；缺失或无法辨识的归入“其他”。",unitSourceNote:"部队单位分类同时参考 Name 与 Details 原文，仅供浏览，未替代史料核验。",unitHeading:"{unit} · {count} 条记录",unitField:"单位归类",unitEmpty:"试试其他姓名，或选择“全部单位”。",unitOtherNote:"这组记录没有明确的单位信息，或原文单位名称无法可靠辨识。",
  title:"里斯本丸号 · 永志纪念 | Lisbon Maru Memorial",description:"翻阅里斯本丸号遇难者纪念册，阅读名单原始记录，为逝者献花。",
  skip:"跳至纪念册",home:"里斯本丸号纪念网站首页",brand:"里斯本丸号",brandSubtitle:"里斯本丸号纪念网站",nav:"主导航",roll:"遇难者纪念册",history:"历史与铭记",sources:"资料说明",language:"选择语言",
  introEyebrow:"永志纪念 · 1942",hero:["海有尽头，","记忆没有。"],subtitle:"里斯本丸号遇难者纪念册",intro:["每一个名字，都是一个曾经鲜活的生命。","在这里，读到他们的名字，留下你的缅怀。"],dedication:["他们的名字，","永存于记忆。"],dedicatedTo:"致未能归来的人们",date:"1942年10月1—2日",sea:"东海 · 里斯本丸号",wreckCoordinate:"沉船点坐标",
  rollEyebrow:"遇难者纪念册",rollHeading:"名字，值得被记住。",recordCount:"条名单记录",clickPrompt:"点击姓名，阅读资料与献花",searchLabel:"检索姓名或原始资料",searchPlaceholder:"检索姓名、服役单位或编号…",clear:"清除检索",sort:"按姓氏 A–Z 排列",alphabetLabel:"按姓氏首字母筛选",all:"全部",found:"找到 {count} 条记录",names:"遇难者姓名",zero:"0 条记录",read:"阅读记录",emptyTitle:"未找到对应记录",emptyBody:"试试姓氏、名字的一部分，或取消首字母筛选。",reset:"查看全部名单",rollFooter:"谨以此册，向每一位逝者致意。",pagination:"纪念册分页",previous:"上一页",next:"下一页",
  historyEyebrow:"铭记这段历史",historyHeading:["铭记生命，","也铭记历史。"],historyLink:"阅读 LiMMA 历史资料",historyBody:["1942年，里斯本丸号载着从香港被运往日本的战俘驶入东海。10月1日，船只遭美国潜艇鱼雷击中；次日沉没。众多生命在这场灾难中逝去，中国舟山渔民参与营救了落水人员。","这本纪念册从姓名开始。让历史中的数字重新成为一个个名字，让遥远的往事仍与今天的我们相连。"],historySource:"历史参考：Lisbon Maru Memorial Association（LiMMA）",
  sourcesEyebrow:"资料说明",sourcesHeading:"关于这份名单",sourceBody:["本册收录所提供 CSV 中的全部 {count} 条记录。同名记录分别保留，未经独立核验的拼写与缩写按原文呈现。名单条数仅表示本文件的收录量，不代表已核实的遇难总人数。","人物详情来自名单中的 Name 与 Details 字段；缺失资料标注为“名单未提供”。人物照片与完整生平将在获得可靠资料后补充。"],download:"下载本册原始名单",footerBrand:"里斯本丸号 · 永志纪念",footerNote:"以尊重守护记忆 · 以铭记祈愿和平",top:"返回顶部",
  close:"关闭人物资料",memoryEyebrow:"深切缅怀",personDescription:"里斯本丸号遇难者 · 名单记录",original:"名单原始记录",nameLabel:"姓名 · Name",detailsLabel:"资料 · Details",missing:"名单未提供",recordNote:"资料按原始名单逐字保留。缩写、拼写及字段含义尚未逐项核验。",sourceRow:"来源：所提供的遇难名单 CSV · 第 {row} 行",tributeTitle:"为这个名字，留一份思念。",tributeBody:"献上一朵花，表达你的缅怀。",saving:"正在保存…",remembered:"已献花 · 感谢你的铭记",flower:"献一朵花",loading:"献花记录读取中",unavailable:"献花记录暂时无法读取",flowerCount:"{count} 份缅怀，留在这里",tributeNote:"每位访客可为每位逝者献花一次。",retry:"重新读取",readError:"暂时无法读取献花记录，请稍后重试。",saveError:"献花未能保存，请重试。",closing:"愿逝者安息，愿记忆长存。",closingEnglish:"我们将永远铭记他们",toolTitle:"检索遇难者纪念册",toolDescription:"按姓名或原始资料检索纪念册，并更新可见结果。",toolError:"请输入不超过120字符的检索词",
 },
 en: {
  viewLabel:"Browse the memorial",byName:"By name",byUnit:"By unit",unitLabel:"Service unit / organisation",allUnits:"All units",unitNote:"Grouped by the unit names in the list, with clear spelling variants combined. Missing or unreadable units are listed under Other.",unitSourceNote:"Unit grouping uses the original Name and Details fields as a browsing aid, not as independent historical verification.",unitHeading:"{unit} · {count} records",unitField:"Unit group",unitEmpty:"Try another name, or select All units.",unitOtherNote:"These records have no explicit unit, or the original unit name cannot be reliably identified.",
  title:"Lisbon Maru · In Remembrance",description:"Explore the Lisbon Maru memorial roll, read original records and leave a flower in remembrance.",
  skip:"Skip to the memorial roll",home:"Lisbon Maru Memorial home",brand:"Lisbon Maru",brandSubtitle:"LISBON MARU MEMORIAL",nav:"Main navigation",roll:"Memorial roll",history:"History & remembrance",sources:"About the records",language:"Choose language",
  introEyebrow:"IN REMEMBRANCE · 1942",hero:["The sea has an end.","Memory does not."],subtitle:"The Lisbon Maru memorial roll",intro:["Every name belongs to a life once lived.","Read their names. Leave a gesture of remembrance."],dedication:["Their names","live on."],dedicatedTo:"For those who never returned",date:"1–2 OCTOBER 1942",sea:"East China Sea · Lisbon Maru",wreckCoordinate:"Wreck coordinates",
  rollEyebrow:"THE ROLL OF REMEMBRANCE",rollHeading:"Every name deserves remembrance.",recordCount:"records",clickPrompt:"Select a name to read their record and leave a flower",searchLabel:"Search names or original details",searchPlaceholder:"Search a name, unit or service number…",clear:"Clear search",sort:"Surnames A–Z",alphabetLabel:"Filter by surname initial",all:"All",found:"{count} records found",names:"Names of the deceased",zero:"0 records",read:"Read record",emptyTitle:"No matching records",emptyBody:"Try part of a name, or clear the initial filter.",reset:"View all records",rollFooter:"In remembrance of every life lost.",pagination:"Memorial roll pages",previous:"Previous page",next:"Next page",
  historyEyebrow:"A HISTORY WE REMEMBER",historyHeading:["Remembering lives.","Remembering history."],historyLink:"Read the history at LiMMA",historyBody:["In 1942, the Lisbon Maru sailed into the East China Sea carrying prisoners of war from Hong Kong to Japan. On 1 October, the ship was struck by a torpedo from an American submarine; it sank the following day. Many lives were lost. Chinese fishermen from the Zhoushan islands helped rescue men from the sea.","This memorial begins with names, remembering the individuals behind the numbers and keeping their story connected to the present."],historySource:"Historical reference: Lisbon Maru Memorial Association (LiMMA)",
  sourcesEyebrow:"ABOUT THE RECORDS",sourcesHeading:"About this list",sourceBody:["This memorial includes all {count} records from the supplied CSV. People with the same name are kept as separate entries. Spellings and abbreviations are reproduced as supplied and have not been independently verified. The record count describes this file, not a verified total of those who died.","Personal details come from the Name and Details fields in the list. Missing information is marked ‘Not provided in the list’. Photographs and full biographies can be added when reliable material becomes available."],download:"Download the original list",footerBrand:"Lisbon Maru · In Remembrance",footerNote:"Respecting memory · Remembering for peace",top:"Back to top",
  close:"Close personal record",memoryEyebrow:"IN LOVING MEMORY",personDescription:"Lisbon Maru casualty · List entry",original:"Original list record",nameLabel:"Name",detailsLabel:"Details",missing:"Not provided in the list",recordNote:"The original record is reproduced verbatim. Abbreviations, spellings and their meanings have not yet been individually verified.",sourceRow:"Source: supplied casualty CSV · Row {row}",tributeTitle:"A gesture of remembrance.",tributeBody:"Leave a flower in their memory.",saving:"Saving…",remembered:"Flower left · Thank you for remembering",flower:"Leave a flower",loading:"Loading remembrance records",unavailable:"Remembrance records are unavailable",flowerCount:"{count} gestures of remembrance",tributeNote:"Each visitor may leave one flower for each person.",retry:"Try again",readError:"Unable to load remembrance records. Please try again later.",saveError:"Your flower could not be saved. Please try again.",closing:"May they rest in peace. May their memory endure.",closingEnglish:"WE WILL REMEMBER THEM",toolTitle:"Search the memorial roll",toolDescription:"Search names or original details and update the visible memorial records.",toolError:"Enter a search term of no more than 120 characters",
 },
 ja: {
  viewLabel:"名簿の閲覧方法",byName:"名前で見る",byUnit:"部隊・所属別に見る",unitLabel:"部隊・所属組織",allUnits:"すべての部隊・所属",unitNote:"名簿の所属名に基づき、明確な綴りの違いは同じ分類にまとめています。記載がない場合や判読できない場合は「その他」に分類しています。",unitSourceNote:"部隊・所属の分類は Name と Details の原文を参照した閲覧用の整理であり、独立した史料検証を意味するものではありません。",unitHeading:"{unit} · {count} 件の記録",unitField:"部隊・所属の分類",unitEmpty:"別の名前で検索するか、すべての部隊・所属を選択してください。",unitOtherNote:"所属が明記されていないか、原文の所属名を確実に判別できない記録です。",
  title:"リスボン丸 · 追悼の記録",description:"リスボン丸の犠牲者名簿を読み、原記録をたどり、追悼の花を捧げることができます。",
  skip:"追悼名簿へ移動",home:"リスボン丸追悼サイト ホーム",brand:"リスボン丸",brandSubtitle:"リスボン丸 追悼サイト",nav:"メインナビゲーション",roll:"犠牲者名簿",history:"歴史と記憶",sources:"資料について",language:"言語を選択",
  introEyebrow:"追悼 · 1942",hero:["海には果てがある。","記憶には、ない。"],subtitle:"リスボン丸 犠牲者追悼名簿",intro:["一つひとつの名前に、生きていた一人の人生があります。","その名前を読み、追悼の思いを寄せてください。"],dedication:["その名前を、","忘れない。"],dedicatedTo:"帰還できなかった人々へ",date:"1942年10月1日–2日",sea:"東シナ海 · リスボン丸",wreckCoordinate:"沈没地点の座標",
  rollEyebrow:"追悼の名簿",rollHeading:"一人ひとりの名前を、記憶に。",recordCount:"件の記録",clickPrompt:"名前を選ぶと、記録を読み、花を捧げられます",searchLabel:"名前または原記録を検索",searchPlaceholder:"名前・所属部隊・軍籍番号を検索…",clear:"検索をクリア",sort:"姓のアルファベット順 A–Z",alphabetLabel:"姓の頭文字で絞り込む",all:"すべて",found:"{count} 件の記録が見つかりました",names:"犠牲者の名前",zero:"0 件の記録",read:"記録を読む",emptyTitle:"該当する記録がありません",emptyBody:"名前の一部で検索するか、頭文字の絞り込みを解除してください。",reset:"すべての記録を表示",rollFooter:"失われた一つひとつの命に、追悼の意を込めて。",pagination:"追悼名簿のページ",previous:"前のページ",next:"次のページ",
  historyEyebrow:"記憶にとどめる歴史",historyHeading:["命を忘れない。","歴史を忘れない。"],historyLink:"LiMMA の歴史資料を読む",historyBody:["1942年、リスボン丸は香港から日本へ移送される捕虜を乗せ、東シナ海を航行していました。10月1日、アメリカ潜水艦の魚雷を受け、翌日に沈没しました。多くの人々が命を落とし、中国・舟山諸島の漁民が海に投げ出された人々の救助にあたりました。","この追悼名簿は、名前から始まります。数字の向こうにいた一人ひとりを思い起こし、その歴史を今を生きる私たちにつなぎます。"],historySource:"歴史資料：Lisbon Maru Memorial Association（LiMMA）",
  sourcesEyebrow:"記録について",sourcesHeading:"この名簿について",sourceBody:["提供された CSV の全 {count} 件の記録を収録しています。同じ名前の記録も別々に保存し、独立した確認が済んでいない綴りや略語は原文のまま掲載しています。この件数はファイルの収録数であり、確認済みの犠牲者総数を示すものではありません。","人物の情報は名簿の Name と Details 欄に基づいています。情報がない場合は「名簿に記載なし」と表示します。写真や詳しい経歴は、信頼できる資料が得られた際に追加できます。"],download:"原名簿をダウンロード",footerBrand:"リスボン丸 · 追悼の記録",footerNote:"記憶を尊重し、平和を願う",top:"ページ上部へ",
  close:"人物の記録を閉じる",memoryEyebrow:"追悼の思いを込めて",personDescription:"リスボン丸の犠牲者 · 名簿の記録",original:"名簿の原記録",nameLabel:"氏名 · Name",detailsLabel:"詳細 · Details",missing:"名簿に記載なし",recordNote:"情報は原名簿の記載をそのまま掲載しています。略語、綴り、各項目の意味は、まだ個別に検証されていません。",sourceRow:"出典：提供された犠牲者名簿 CSV · {row} 行目",tributeTitle:"この名前に、追悼の思いを。",tributeBody:"一輪の花を捧げて、哀悼の意を表してください。",saving:"保存しています…",remembered:"献花しました · 追悼に感謝します",flower:"花を捧げる",loading:"献花の記録を読み込んでいます",unavailable:"献花の記録を読み込めません",flowerCount:"{count} 件の追悼の思いが寄せられています",tributeNote:"一人の訪問者につき、各人に一度献花できます。",retry:"再試行",readError:"献花の記録を読み込めません。しばらくしてから再試行してください。",saveError:"献花を保存できませんでした。再試行してください。",closing:"安らかな眠りを。その記憶が永く続きますように。",closingEnglish:"WE WILL REMEMBER THEM",toolTitle:"追悼名簿を検索",toolDescription:"名前または原記録を検索し、表示される名簿を更新します。",toolError:"120文字以内の検索語を入力してください",
 },
} as const;
export const formatText = (text: string, values: Record<string,string|number>) => text.replace(/\{(\w+)\}/g, (_,key:string) => String(values[key] ?? ""));

export const numberLocales = {zh:"zh-CN",en:"en-GB",ja:"ja-JP",fr:"fr-FR",ko:"ko-KR",es:"es-ES",ar:"ar"} as const;
export const formatNumber = (value:number, locale:Locale) => value.toLocaleString(numberLocales[locale]);
export const formatPercent = (value:number, locale:Locale) => new Intl.NumberFormat(numberLocales[locale],{style:"percent",maximumFractionDigits:2}).format(value / 100);
