import type { Locale } from './i18n';
const zh={nav:'献花纪念',eyebrow:'纪念仪式 · 一朵花，一份记忆',title:'献上一朵花，让828份记忆亮起。',intro:'以虞美人，纪念在里斯本丸号事件中遇难的828名英国战俘。',instruction:'将红花拖入后方的花形区域，也可以点击红花献花。',offer:'献上一朵虞美人',drop:'将花放在这里',lighting:'记忆正在亮起…',complete:'828朵花，为828个生命亮起。',field:'828朵纪念虞美人',count:'朵花已亮起',again:'再次献花'};
export const poppyTranslations:Record<Locale,typeof zh>={zh,
 en:{nav:'Offer a poppy',eyebrow:'AN ACT OF REMEMBRANCE',title:'One poppy. 828 memories brought to light.',intro:'Remember the 828 British prisoners of war who died in the Lisbon Maru incident with a corn poppy.',instruction:'Drag the red poppy onto the flower behind it, or select the red poppy to offer it.',offer:'Offer a corn poppy',drop:'Place your poppy here',lighting:'Memories are lighting up…',complete:'828 poppies, glowing for 828 lives.',field:'828 remembrance poppies',count:'poppies illuminated',again:'Offer a poppy again'},
 ja:{nav:'花を手向ける',eyebrow:'追悼の儀式 · 一輪に記憶を',title:'一輪の花から、828の記憶に光を。',intro:'里斯本丸号事件で命を落とした828名の英国人捕虜を、ヒナゲシの花で追悼します。',instruction:'赤い花を後ろの花形の場所へドラッグしてください。赤い花を押して手向けることもできます。',offer:'ヒナゲシを手向ける',drop:'ここに花を置く',lighting:'記憶に光が灯っています…',complete:'828の命へ、828輪の花が灯りました。',field:'828輪の追悼のヒナゲシ',count:'輪の花が点灯',again:'もう一度花を手向ける'},
 fr:{nav:'Offrir un coquelicot',eyebrow:'UN GESTE DE SOUVENIR',title:'Une fleur pour éclairer 828 mémoires.',intro:'Un coquelicot en mémoire des 828 prisonniers de guerre britanniques morts lors du naufrage du Lisbon Maru.',instruction:'Glissez le coquelicot rouge sur la fleur derrière lui, ou sélectionnez-le pour le déposer.',offer:'Offrir un coquelicot',drop:'Déposez votre fleur ici',lighting:'Les mémoires s’illuminent…',complete:'828 coquelicots brillent pour 828 vies.',field:'828 coquelicots du souvenir',count:'coquelicots illuminés',again:'Offrir à nouveau une fleur'},
 ko:{nav:'꽃으로 추모하기',eyebrow:'추모 의식 · 한 송이에 담은 기억',title:'한 송이 꽃으로, 828명의 기억을 밝힙니다.',intro:'리스본 마루호 사건으로 목숨을 잃은 영국군 포로 828명을 개양귀비로 추모합니다.',instruction:'빨간 꽃을 뒤의 꽃 모양 영역으로 끌어다 놓으세요. 빨간 꽃을 눌러 헌화할 수도 있습니다.',offer:'개양귀비 헌화하기',drop:'여기에 꽃을 놓아 주세요',lighting:'기억이 빛나고 있습니다…',complete:'828명의 삶을 위해 828송이 꽃이 빛납니다.',field:'추모의 개양귀비 828송이',count:'송이의 꽃이 빛납니다',again:'다시 헌화하기'},
 es:{nav:'Ofrecer una amapola',eyebrow:'UN GESTO DE RECUERDO',title:'Una flor ilumina 828 memorias.',intro:'Una amapola en recuerdo de los 828 prisioneros de guerra británicos que murieron en el incidente del Lisbon Maru.',instruction:'Arrastra la amapola roja sobre la flor que hay detrás, o selecciónala para ofrecerla.',offer:'Ofrecer una amapola',drop:'Deja aquí tu flor',lighting:'Las memorias se iluminan…',complete:'828 amapolas brillan por 828 vidas.',field:'828 amapolas del recuerdo',count:'amapolas iluminadas',again:'Volver a ofrecer una flor'},
 ar:{nav:'إهداء زهرة',eyebrow:'طقس للتذكّر · زهرة تحمل ذكرى',title:'زهرة واحدة تضيء 828 ذكرى.',intro:'زهرة خشخاش تذكّرنا بأسرى الحرب البريطانيين الـ828 الذين فقدوا حياتهم في حادثة لشبونة مارو.',instruction:'اسحب الزهرة الحمراء إلى شكل الزهرة خلفها، أو اضغط على الزهرة الحمراء لإهدائها.',offer:'إهداء زهرة خشخاش',drop:'ضع الزهرة هنا',lighting:'الذكريات تضيء…',complete:'828 زهرة تضيء من أجل 828 حياة.',field:'828 زهرة خشخاش للتذكّر',count:'زهرة مضاءة',again:'إهداء زهرة من جديد'}
};
