import type { Locale } from './i18n';
const zh={nav:'观众留言',eyebrow:'阅读之后 · 留下回响',title:'让记忆，在此刻相连。',intro:'写下你的读后感、缅怀与对和平的思考。',name:'署名（选填）',namePlaceholder:'你希望展示的名字',message:'你的读后感（选填）',placeholder:'哪一个名字、哪一段故事，留在了你的心里？',notice:'保存后，留言会公开展示。请尊重彼此，不填写私人联系方式。',ownership:'你可以删除自己的留言。未登录时，请使用保存留言的同一浏览器。',save:'保存留言',saving:'保存中…',saved:'留言已保存，谢谢你留下这份回响。',delete:'删除',confirm:'确认删除这条留言？',yes:'确认删除',cancel:'取消',deleting:'删除中…',deleted:'留言已删除。',list:'观众的回响',empty:'这里还没有留言。你可以留下第一份感想。',anonymous:'一位访客',mine:'我的留言',loading:'正在读取留言…',readError:'暂时无法读取留言，请稍后重试。',saveError:'留言未能保存，输入的内容已保留，请重试。',deleteError:'未能删除留言，请重试。',wait:'留言发送得有些频繁，请稍等一分钟再保存。',retry:'重试',previous:'上一页',next:'下一页',count:'条留言',page:'留言分页'};
export const visitorReflectionTranslations:Record<Locale,{[K in keyof typeof zh]:string}>={zh,
 en:{nav:'Visitor reflections',eyebrow:'AFTER READING · AN ECHO',title:'Memory connects us, here and now.',intro:'Leave a reflection, a remembrance, or a thought about peace.',name:'Display name (optional)',namePlaceholder:'The name you would like to display',message:'Your reflection (optional)',placeholder:'Which name or story has stayed with you?',notice:'Saved reflections are public. Please respect others and leave out private contact details.',ownership:'You can delete your own reflections. If you are not signed in, use the same browser you saved them in.',save:'Save reflection',saving:'Saving…',saved:'Your reflection is saved. Thank you for remembering.',delete:'Delete',confirm:'Delete this reflection?',yes:'Confirm deletion',cancel:'Cancel',deleting:'Deleting…',deleted:'Reflection deleted.',list:'Voices of our visitors',empty:'No reflections yet. You can leave the first.',anonymous:'A visitor',mine:'My reflection',loading:'Loading reflections…',readError:'Reflections could not be loaded. Please try again.',saveError:'Your reflection could not be saved. Your writing is still here; please try again.',deleteError:'The reflection could not be deleted. Please try again.',wait:'Please wait a minute before saving another reflection.',retry:'Try again',previous:'Previous',next:'Next',count:'reflections',page:'Reflection pages'},
 ja:{nav:'来訪者の感想',eyebrow:'読んだあとに · 思いを残す',title:'記憶が、今の私たちをつなぐ。',intro:'読後の感想、追悼の思い、平和への願いをお寄せください。',name:'表示名（任意）',namePlaceholder:'表示したいお名前',message:'あなたの感想（任意）',placeholder:'心に残った名前や物語はありますか。',notice:'保存した感想は公開されます。他の方を尊重し、個人の連絡先は記載しないでください。',ownership:'自分の感想は削除できます。ログインしていない場合は、保存したときと同じブラウザーをお使いください。',save:'感想を保存',saving:'保存中…',saved:'感想を保存しました。思いを寄せてくださりありがとうございます。',delete:'削除',confirm:'この感想を削除しますか？',yes:'削除する',cancel:'キャンセル',deleting:'削除中…',deleted:'感想を削除しました。',list:'来訪者の声',empty:'まだ感想はありません。最初の思いを残してみませんか。',anonymous:'ある来訪者',mine:'自分の感想',loading:'感想を読み込んでいます…',readError:'感想を読み込めませんでした。再試行してください。',saveError:'保存できませんでした。入力内容は残っています。再試行してください。',deleteError:'削除できませんでした。再試行してください。',wait:'次の感想を保存するまで、1分ほどお待ちください。',retry:'再試行',previous:'前へ',next:'次へ',count:'件の感想',page:'感想のページ'},
 fr:{nav:'Vos impressions',eyebrow:'APRÈS LA LECTURE · UN ÉCHO',title:'La mémoire nous relie, ici et maintenant.',intro:'Partagez une impression, un hommage ou une pensée pour la paix.',name:'Nom affiché (facultatif)',namePlaceholder:'Le nom que vous souhaitez afficher',message:'Votre réflexion (facultative)',placeholder:'Quel nom ou quelle histoire vous a marqué ?',notice:'Les réflexions enregistrées sont publiques. Respectez les autres et ne publiez pas de coordonnées personnelles.',ownership:'Vous pouvez supprimer vos propres réflexions. Sans connexion, utilisez le navigateur dans lequel vous les avez enregistrées.',save:'Enregistrer',saving:'Enregistrement…',saved:'Votre réflexion est enregistrée. Merci pour cet hommage.',delete:'Supprimer',confirm:'Supprimer cette réflexion ?',yes:'Confirmer',cancel:'Annuler',deleting:'Suppression…',deleted:'Réflexion supprimée.',list:'Les voix de nos visiteurs',empty:'Aucune réflexion pour le moment. Vous pouvez laisser la première.',anonymous:'Un visiteur',mine:'Ma réflexion',loading:'Chargement des réflexions…',readError:'Impossible de charger les réflexions. Réessayez.',saveError:'Impossible d’enregistrer. Votre texte est conservé ; réessayez.',deleteError:'Impossible de supprimer cette réflexion. Réessayez.',wait:'Attendez une minute avant d’enregistrer une autre réflexion.',retry:'Réessayer',previous:'Précédent',next:'Suivant',count:'réflexions',page:'Pages des réflexions'},
 ko:{nav:'방문자 소감',eyebrow:'읽은 뒤 · 마음을 남기다',title:'기억은 지금의 우리를 이어 줍니다.',intro:'읽고 느낀 점, 추모의 마음, 평화에 대한 생각을 남겨 주세요.',name:'표시 이름 (선택)',namePlaceholder:'표시하고 싶은 이름',message:'나의 소감 (선택)',placeholder:'어떤 이름이나 이야기가 마음에 남았나요?',notice:'저장한 소감은 공개됩니다. 서로를 존중하고 개인 연락처는 적지 말아 주세요.',ownership:'자신의 소감은 삭제할 수 있습니다. 로그인하지 않았다면 저장할 때 사용한 브라우저를 이용해 주세요.',save:'소감 저장',saving:'저장 중…',saved:'소감을 저장했습니다. 기억해 주셔서 감사합니다.',delete:'삭제',confirm:'이 소감을 삭제할까요?',yes:'삭제 확인',cancel:'취소',deleting:'삭제 중…',deleted:'소감을 삭제했습니다.',list:'방문자의 목소리',empty:'아직 소감이 없습니다. 첫 번째 마음을 남겨 주세요.',anonymous:'한 방문자',mine:'내 소감',loading:'소감을 불러오는 중…',readError:'소감을 불러오지 못했습니다. 다시 시도해 주세요.',saveError:'저장하지 못했습니다. 입력한 글은 그대로 남아 있습니다. 다시 시도해 주세요.',deleteError:'삭제하지 못했습니다. 다시 시도해 주세요.',wait:'다음 소감을 저장하기 전에 1분만 기다려 주세요.',retry:'다시 시도',previous:'이전',next:'다음',count:'개의 소감',page:'소감 페이지'},
 es:{nav:'Reflexiones de visitantes',eyebrow:'TRAS LA LECTURA · UN ECO',title:'La memoria nos une, aquí y ahora.',intro:'Comparte una reflexión, un homenaje o un pensamiento sobre la paz.',name:'Nombre visible (opcional)',namePlaceholder:'El nombre que deseas mostrar',message:'Tu reflexión (opcional)',placeholder:'¿Qué nombre o historia se ha quedado contigo?',notice:'Las reflexiones guardadas son públicas. Respeta a los demás y no incluyas datos de contacto privados.',ownership:'Puedes eliminar tus propias reflexiones. Si no has iniciado sesión, utiliza el mismo navegador en el que las guardaste.',save:'Guardar reflexión',saving:'Guardando…',saved:'Tu reflexión se ha guardado. Gracias por recordar.',delete:'Eliminar',confirm:'¿Eliminar esta reflexión?',yes:'Confirmar eliminación',cancel:'Cancelar',deleting:'Eliminando…',deleted:'Reflexión eliminada.',list:'Las voces de nuestros visitantes',empty:'Todavía no hay reflexiones. Puedes dejar la primera.',anonymous:'Un visitante',mine:'Mi reflexión',loading:'Cargando reflexiones…',readError:'No se pudieron cargar las reflexiones. Inténtalo de nuevo.',saveError:'No se pudo guardar. Tu texto sigue aquí; inténtalo de nuevo.',deleteError:'No se pudo eliminar la reflexión. Inténtalo de nuevo.',wait:'Espera un minuto antes de guardar otra reflexión.',retry:'Reintentar',previous:'Anterior',next:'Siguiente',count:'reflexiones',page:'Páginas de reflexiones'},
 ar:{nav:'تأملات الزوار',eyebrow:'بعد القراءة · صدى يبقى',title:'تجمعنا الذاكرة، هنا والآن.',intro:'اكتب انطباعك بعد القراءة، أو كلمات تذكّر، أو فكرة عن السلام.',name:'الاسم المعروض (اختياري)',namePlaceholder:'الاسم الذي تود عرضه',message:'تأملك (اختياري)',placeholder:'أي اسم أو قصة بقي معك؟',notice:'ستظهر التأملات المحفوظة للجميع. يرجى احترام الآخرين وعدم كتابة بيانات اتصال خاصة.',ownership:'يمكنك حذف تأملاتك. إذا لم تسجل الدخول، فاستخدم المتصفح نفسه الذي حفظتها فيه.',save:'حفظ التأمل',saving:'جارٍ الحفظ…',saved:'تم حفظ تأملك. شكراً لك على التذكّر.',delete:'حذف',confirm:'هل تريد حذف هذا التأمل؟',yes:'تأكيد الحذف',cancel:'إلغاء',deleting:'جارٍ الحذف…',deleted:'تم حذف التأمل.',list:'أصوات زوارنا',empty:'لا توجد تأملات بعد. يمكنك كتابة أول تأمل.',anonymous:'أحد الزوار',mine:'تأملي',loading:'جارٍ تحميل التأملات…',readError:'تعذر تحميل التأملات. يرجى المحاولة مجدداً.',saveError:'تعذر الحفظ. ما كتبته ما زال هنا؛ يرجى المحاولة مجدداً.',deleteError:'تعذر حذف التأمل. يرجى المحاولة مجدداً.',wait:'يرجى الانتظار دقيقة قبل حفظ تأمل آخر.',retry:'المحاولة مجدداً',previous:'السابق',next:'التالي',count:'تأملات',page:'صفحات التأملات'}
};
const attachmentZh={addFiles:'添加图片或文件',attachmentNote:'可只添加图片或文件，无需填写文字。最多 3 个文件，每个不超过 5 MB。保存后附件会公开展示。',removeFile:'移除附件',download:'下载附件',attachments:'留言附件',fileCount:'每条留言最多添加 3 个文件。',fileSize:'请选择非空文件，每个文件不超过 5 MB。'};
export const reflectionAttachmentTranslations:Record<Locale,{[K in keyof typeof attachmentZh]:string}>={
 zh:attachmentZh,
 en:{addFiles:'Add images or files',attachmentNote:'You can add images or files without writing a reflection. Up to 3 files, 5 MB each. Attachments become public when saved.',removeFile:'Remove attachment',download:'Download attachment',attachments:'Reflection attachments',fileCount:'You can add up to 3 files per reflection.',fileSize:'Choose a non-empty file no larger than 5 MB.'},
 ja:{addFiles:'画像・ファイルを追加',attachmentNote:'文章を入力せずに、画像やファイルだけを追加できます。最大3件、1件につき5 MBまで。保存後、添付ファイルは公開されます。',removeFile:'添付を取り除く',download:'添付をダウンロード',attachments:'感想の添付ファイル',fileCount:'1件の感想に添付できるファイルは3件までです。',fileSize:'空でない5 MB以下のファイルを選んでください。'},
 fr:{addFiles:'Ajouter des images ou fichiers',attachmentNote:'Vous pouvez ajouter des images ou fichiers sans texte. 3 fichiers maximum, 5 Mo chacun. Les pièces jointes seront publiques après enregistrement.',removeFile:'Retirer la pièce jointe',download:'Télécharger la pièce jointe',attachments:'Pièces jointes',fileCount:'Vous pouvez joindre jusqu’à 3 fichiers par réflexion.',fileSize:'Choisissez un fichier non vide de 5 Mo maximum.'},
 ko:{addFiles:'이미지 또는 파일 추가',attachmentNote:'글 없이 이미지나 파일만 추가할 수 있습니다. 최대 3개, 파일당 5 MB까지 가능합니다. 저장한 첨부 파일은 공개됩니다.',removeFile:'첨부 파일 제거',download:'첨부 파일 다운로드',attachments:'소감 첨부 파일',fileCount:'소감 하나에 파일을 최대 3개까지 첨부할 수 있습니다.',fileSize:'비어 있지 않은 5 MB 이하의 파일을 선택해 주세요.'},
 es:{addFiles:'Añadir imágenes o archivos',attachmentNote:'Puedes añadir imágenes o archivos sin escribir texto. Hasta 3 archivos, de 5 MB cada uno. Los adjuntos serán públicos al guardar.',removeFile:'Quitar adjunto',download:'Descargar adjunto',attachments:'Archivos adjuntos',fileCount:'Puedes añadir hasta 3 archivos por reflexión.',fileSize:'Elige un archivo que no esté vacío y no supere los 5 MB.'},
 ar:{addFiles:'إضافة صور أو ملفات',attachmentNote:'يمكنك إضافة صور أو ملفات دون كتابة نص. حتى 3 ملفات، بحجم 5 ميغابايت لكل ملف. ستظهر المرفقات للجميع بعد الحفظ.',removeFile:'إزالة المرفق',download:'تنزيل المرفق',attachments:'مرفقات التأمل',fileCount:'يمكنك إرفاق 3 ملفات كحد أقصى بكل تأمل.',fileSize:'اختر ملفاً غير فارغ لا يتجاوز حجمه 5 ميغابايت.'}
};
